### ISSUE TITLE
Error when ran without MAFFT

### ISSUE THREAD

**Issue by ivopieniak** [wurmlab/genevalidator#149]
```
Traceback (most recent call last):
	7: from /usr/local/bin/genevalidator:23:in `<main>'
	6: from /usr/local/bin/genevalidator:23:in `load'
	5: from /var/lib/gems/2.5.0/gems/genevalidator-2.1.5/bin/genevalidator:357:in `<top (required)>'
	4: from /var/lib/gems/2.5.0/gems/genevalidator-2.1.5/lib/genevalidator.rb:59:in `run'
	3: from /var/lib/gems/2.5.0/gems/genevalidator-2.1.5/lib/genevalidator.rb:100:in `produce_output'
	2: from /var/lib/gems/2.5.0/gems/genevalidator-2.1.5/lib/genevalidator/output.rb:113:in `generate_overview'
	1: from /var/lib/gems/2.5.0/gems/genevalidator-2.1.5/lib/genevalidator/ext/array.rb:40:in `all_quartiles'
/var/lib/gems/2.5.0/gems/genevalidator-2.1.5/lib/genevalidator/ext/array.rb:15:in `median': undefined method `+' for nil:NilClass (NoMethodError)
```
/cc @yeban

**Comment by IsmailM** [comment]
Hey @ivopieniak,

Can you provide further info?

I see that you have installed GV via RubyGems? The recommended way to install GV is via the standalone installation: e.g.:

```
# Run this wherever you want to install GV
sh -c "$(curl -fsSL https://install-genevalidator.wurmlab.com)"
```

This will automatically install all dependencies (e.g. mafft etc.) and also add this to the $PATH...

**Comment by IsmailM** [comment]
Closing this due to lack of response - assuming this is fixed.

Please reopen if required :)
