### ISSUE TITLE
Web app unable to load and output without graphs

### ISSUE THREAD

**Issue by Clemseth** [wurmlab/genevalidator#151]
Two issues here: 

1) App/ online component will no load: when run an error message appears: 
```Input: genevalidator app --num_threads 4
Output: /path/to/user/genevalidator/lib/ruby/lib/ruby/gems/2.2.0/gems/bundler-1.9.9/lib/bundler/shared_helpers.rb:78: warning: Insecure world writable dir /Bio338/warners2 in PATH, mode 040777
Something went wonky
Looks like you have encountered a bug in GeneValidatorApp. Please could you
report this incident here -
https://github.com/wurmlab/genevalidator/issues
Error:
undefined method `match' for nil:NilClass
/path/to/user/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.7/lib/genevalidatorapp/database.rb:91:in `multipart_database_name?'
/path/to/user/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.7/lib/genevalidatorapp/database.rb:77:in `block in scan_databases_dir'
/path/to/user/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.7/lib/genevalidatorapp/database.rb:75:in `each_line'
/path/to/user/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.7/lib/genevalidatorapp/database.rb:75:in `scan_databases_dir'
/path/to/user/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.7/lib/genevalidatorapp.rb:133:in `init_database'
/path/to/user/genevalidator/lib/vendor/ruby/2.2.0/gems/genevalidatorapp-2.1.7/lib/genevalidatorapp.rb:43:in `init'
/path/to/user/genevalidator/bin/../lib/app/bin/genevalidator:488:in `<main>'"
```
2) Additionally graphs are not appearing on the html files, even on the exemplar data. I am unsure of the underlying cause

**Comment by IsmailM** [comment]
Hi @Clemseth,

Sorry to hear you are having issues running GeneValidator. 

Any further information on how you installed GeneValidator, the commands you ran, and which BLAST databases you have, would be most useful.

With regards to the graphs on the HTML files, are you opening the HTML files directly or using the `genevalidator serve` command? 

(Previously, it used to open the HTML files directly, but most browsers have now disabled the mechanism of how we were loading data in the browser, as such it is now necessary to open the HTML files with the `genevalidator serve` command. I plan to release a new update soon where an error message is shown if opening the HTML files directly).

As such, the following commands work:

```bash
# Install Genevalidator
sh -c "$(curl -fsSL https://raw.githubusercontent.com/wurmlab/genevalidator/master/install.sh)"

# go into the Genevalidator folder
cd genevalidator

# run GeneValidator against the exemplar data
./genevalidator --db ./blast_db/swissprot --num_threads 4 ./exemplar_data/protein_data.fa

# This will produce a folder named similar to `protein_data_2020_06_27_16_46_19`
# (the filename will be different based on when you run this).

# Open the HTML files using the `genevalidator serve` command:
genevalidator serve ./protein_data_2020_06_27_16_46_19/

# This will open the results using your default browser.
```

With regards to the first bug, this is likely due to receiving unexpected output from BLAST+. Are you using the default database or have you added your BLAST databases? 

Would you mind trying the following commands and letting me know of the output of the last command.

```bash
# Install Genevalidator (obviously don't install this again if you already have this :) )
sh -c "$(curl -fsSL https://raw.githubusercontent.com/wurmlab/genevalidator/master/install.sh)"

# go into the Genevalidator folder
cd genevalidator

# change the path of ./blast_db if you are using a different blast database
./bin/blastdbcmd  -list_outfmt "%p::%f::%t" -recursive -list ./blast_db
```

**Comment by IsmailM** [comment]
Fixed with the latest [release](https://github.com/wurmlab/genevalidator/releases/tag/2.1.10)
