### ISSUE TITLE
Error trying Diamond input

### ISSUE THREAD

**Issue by eganko** [wurmlab/genevalidator#167]
I'm trying the Blast parse_seqids approach as detailed on
https://github.com/wurmlab/genevalidator/wiki/Using-DIAMOND-with-GV

I've run diamond and the makeblastdb commands, and when I try genevalidator like this:
```
genevalidator -n 1 -d /scratch-large/3-monthly/datasets/uniprot_sprot.fasta -x /home/bioinf/GeneValidator/genevalidator/exemplar_data/protein_data.xml /home/bioinf/GeneValidator/genevalidator/exemplar_data/protein_data.fa
```

I get the following:

```
==> Analysing input arguments
==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No     Score             Identifier    No_Hits LengthCluster   LengthRank      GeneMerge       Duplication     MissingExtraSequences
  1        67             GB10056-PA          8 339 [317, 365]  50%     0.0     1.0     Not enough evidence
/home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator/output.rb:112:in `block in generate_overview': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator/output.rb:112:in `map'
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator/output.rb:112:in `generate_overview'
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator.rb:101:in `produce_output'
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator.rb:59:in `run'
        from /home/bioinf/GeneValidator/genevalidator/bin/../lib/app/bin/genevalidator:423:in `<main>'
```

**Comment by IsmailM** [comment]
Apologies for the delay in getting back to you. 

I have updated the example for using Diamond with GeneValidator - https://github.com/wurmlab/genevalidator/wiki/Using-DIAMOND-with-GV

Can you try this example, with a fresh install of GeneValidator with the exemplar data and let me know if that works?

If that works, please try again with your data. 

If it still does not work, would you be able to share a subset of your input data so that I can debug this?

**Comment by eganko** [comment]
ok, I tried a new install:
```
genevalidator -v
2.1.11
```

then I ran diamond (v.2.1.4) and got the following:
```
Total time = 5.939s
Reported 112 pairwise alignments, 112 HSPs.
9 queries aligned.
```

Then 
```
genevalidator -n 8 -m 4 -d /scratch-large/3-monthly/datasets/uniprot_sprot.fasta -x /home/bioinf/GeneValidator/genevalidator/exemplar_data/protein_data.xml /home/bioinf/GeneValidator/genevalidator/exemplar_data/protein_data.fa  
```

which has the output 
```
==> Analysing input arguments
==> Extracting fasta sequences for each BLAST HSP from the BLAST database
==> Validating input sequences

 No     Score             Identifier    No_Hits LengthCluster   LengthRank      GeneMerge       Duplication     MissingExtraSequences
  1        67             GB10056-PA          8 339 [317, 365]  50%     0.0     1.0     Not enough evidence
/home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator/output.rb:112:in `block in generate_overview': undefined method `[]' for nil:NilClass (NoMethodError)
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator/output.rb:112:in `map'
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator/output.rb:112:in `generate_overview'
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator.rb:101:in `produce_output'
        from /home/bioinf/GeneValidator/genevalidator/lib/vendor/ruby/2.4.0/gems/genevalidator-2.1.11/lib/genevalidator.rb:59:in `run'
        from /home/bioinf/GeneValidator/genevalidator/bin/../lib/app/bin/genevalidator:423:in `<main>'
```

**Comment by IsmailM** [comment]
What version of Diamond do you have?

Would you mind running the following with the included copy of swissprot?

```bash
cd /home/bioinf/GeneValidator/genevalidator

# Install Diamond (see https://github.com/bbuchfink/diamond)
curl -L https://github.com/bbuchfink/diamond/releases/download/v2.1.6/diamond-linux64.tar.gz | tar -xz -C bin

# Make Diamond BLAST database 
./bin/diamond prepdb -d blast_db/swissprot

# Run BLASTP with Diamond
./bin/diamond blastp --db blast_db/swissprot --outfmt 5 --query exemplar_data/protein_data.fa --out exemplar_data/protein_data.xml

# Run GeneValidator with blastXML file produced 
./bin/genevalidator -n 8 -m 4 -d blast_db/swissprot -x exemplar_data/protein_data.xml exemplar_data/protein_data.fa 
```

**Comment by eganko** [comment]
I had diamond v.2.1.4, so I followed your directions and tried v2.1.6 -- that is now working with the exemplar data. I'll try re-running my larger dataset with the 2.1.6 diamond next week.
