### ISSUE TITLE
-j option error

### ISSUE THREAD

**Issue by yeban** [wurmlab/genevalidator#97]
```
iMac:~/wurmlab/genevalidator git:master ➜  genevalidator -j data/protless.fa.json                                                        ruby:2.1.4
/Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:101:in `readlines': No such file or directory @ rb_sysopen - data/protless.fa.json.html/files/js/script.js (Errno::ENOENT)
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:101:in `block in turn_off_automated_sorting'
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:100:in `open'
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:100:in `turn_off_automated_sorting'
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:86:in `write_html_footer'
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:82:in `html_footer'
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/lib/genevalidator/json_to_gv_results.rb:40:in `run'
	from /Users/priyam/.gem/ruby/2.1.4/gems/genevalidator-1.6.4/bin/genevalidator:135:in `<top (required)>'
	from /Users/priyam/.gem/ruby/2.1.4/bin/genevalidator:23:in `load'
	from /Users/priyam/.gem/ruby/2.1.4/bin/genevalidator:23:in `<main>'
```

Path to HTML is incorrectly constructed it seems.

**Comment by yeban** [comment]
Why does it even read the HTML previously generated? Why not create the HTML report anew?
